---
title: "IBM Web Accessibility Report"
options:
  echo: false
  message: false
  results: hide
params:
  excelpath: NULL
  url: NULL
---

<!-- Rmd default behavior options. -->
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```

<!-- Installs / loads required packages. --->
```{r}
packages = c("readxl", "ggplot2", "dplyr", "stringr")

for (pkg in packages) {
  if (!requireNamespace(pkg, quietly = TRUE)) {
    install.packages(pkg, dependencies = TRUE)
  }
}
library(readxl)
library(ggplot2)
library(dplyr)
library(tidyr)
library(stringr)
```

<!-- Imports report. ***ADJUST FILE PATH*** --->
```{r}
data = read_excel(params$excelpath)
```

# Site Details 
<!-- (1) Site Name & URL --->
```{r, results='asis'}
cat("**URL:** ", params$url, "<br>")
cat("**Policies:** ", data$`policies`[1], "<br>")
cat("**Scan ID:** ", data$`scanID`[1], "<br>")
```

# Brief Summary
<!-- (2) Histogram of Issue Types --->
```{r, fig.align="center"}
data |>
  group_by(level) |>
  summarize(n = n()) |>
  ungroup() |>
  complete(level = c("violation", "recommendation", "potentialviolation"), fill = list(n = 0)) |>
  mutate(level = factor(level, levels = c("violation", "recommendation", "potentialviolation"))) |>
  arrange(level) |>

  ggplot(aes(x = `level`, y = n)) +
  geom_bar(stat = "identity", fill = c("#EE4A4A", "#EEEB4A", "#4AA5EE"), color = "black") +
  geom_text(aes(label = n), vjust = -0.5, size = 3) + 
  labs(title = "Histogram of Issue Types",
       x = "Issue Type",
       y = "Count") + 
  scale_y_continuous(breaks = seq(0, 9999, by = 5)) + 
  theme_minimal() + 
  theme(plot.title = element_text(hjust = 0.5))
```

<!-- (3) Histogram of Checkpoints --->
```{r, fig.align="center", fig.height=10}
data |>
  group_by(`message`) |>
  summarize(n = n()) |>
  ungroup() |>
  arrange(desc(n)) |>
  head(7) |>
  
  ggplot(aes(x = reorder(`message`, n), y = n)) +
  geom_bar(stat = "identity", fill = "#A44AEE", width=.8) +
  geom_text(aes(label = n), hjust = -0.5, color = "black") +  
  coord_flip() +
  labs(title = "Histogram of Checkpoints", x = "Checkpoint", y = "Count") +
  theme_minimal() +
  theme(axis.text = element_text(size = 8), 
        plot.title = element_text(hjust = 0.5, size = 12),
        axis.text.x = element_text(angle = 90, hjust = 1)) +
  scale_x_discrete(labels = function(x) str_wrap(x, width = 20))
```

# Violations
<!-- (4) Violations Present --->
```{r, results='asis'}
data |>
  filter(`level` == "violation") |>
  select(c("issueID", "ruleID", "message", "snippet", "dom", "help")) |>  # Select specified columns
  apply(1, function(row) {
    if (!all(is.na(row))) {
      for (col in names(row)) {
        if (!is.na(row[[col]])) {
          cat(col, ": ", htmltools::htmlEscape(row[[col]]), "<br>")
        }
      }
      cat("<br>")
    }
  })
```

# Recommendations
<!-- (5) Recommendations Present --->
```{r, results='asis'}
data |>
  filter(`level` == "recommendation") |>
  select(c("issueID", "ruleID", "message", "snippet", "dom", "help")) |>  # Select specified columns
  apply(1, function(row) {
    if (!all(is.na(row))) {
      for (col in names(row)) {
        if (!is.na(row[[col]])) {
          cat(col, ": ", htmltools::htmlEscape(row[[col]]), "<br>")
        }
      }
      cat("<br>")
    }
  })
```

# Potential Violations
<!-- (5) Recommendations Present --->
```{r, results='asis'}
data |>
  filter(`level` == "potentialviolation") |>
  select(c("issueID", "ruleID", "message", "snippet", "dom", "help")) |>  # Select specified columns
  apply(1, function(row) {
    if (!all(is.na(row))) {
      for (col in names(row)) {
        if (!is.na(row[[col]])) {
          cat(col, ": ", htmltools::htmlEscape(row[[col]]), "<br>")
        }
      }
      cat("<br>")
    }
  })
```

